import type { Finding } from "./types";

export function generateMarkdown(findings: Finding[]): string {
  const lines: string[] = [
    "# PR Review Report",
    "",
    "> Generated by [PR Review Bot](https://pr-review-bot.tomdeluca.dev)",
    "",
  ];

  const summary = {
    critical: findings.filter((f) => f.severity === "critical").length,
    major: findings.filter((f) => f.severity === "major").length,
    minor: findings.filter((f) => f.severity === "minor").length,
  };

  lines.push("## Summary", "");
  lines.push(`| Severity | Count |`);
  lines.push(`|----------|-------|`);
  lines.push(`| 🔴 Critical | ${summary.critical} |`);
  lines.push(`| 🟠 Major    | ${summary.major} |`);
  lines.push(`| 🟡 Minor    | ${summary.minor} |`);
  lines.push(`| **Total**   | **${findings.length}** |`);
  lines.push("");

  const byFile = new Map<string, Finding[]>();
  for (const f of findings) {
    const existing = byFile.get(f.file) ?? [];
    byFile.set(f.file, [...existing, f]);
  }

  for (const [file, fileFindings] of Array.from(byFile)) {
    lines.push(`## \`${file}\``, "");
    for (const f of fileFindings) {
      const icon =
        f.severity === "critical" ? "🔴" : f.severity === "major" ? "🟠" : "🟡";
      lines.push(`### ${icon} ${f.title} — Line ${f.line}`);
      const meta = [
        `**Severity:** ${f.severity}`,
        `**Category:** ${f.category}`,
        f.criterion ? `**Criterion:** ${f.criterion}` : null,
      ]
        .filter(Boolean)
        .join(" · ");
      lines.push(meta, "");
      lines.push(f.message, "");
      lines.push(`> **Suggestion:** ${f.suggestion}`, "");
    }
  }

  return lines.join("\n");
}
